### ISSUE TITLE
Windows and LoopMIDI

### ISSUE THREAD

**Issue by bpmb82** [Boddlnagg/midir#149]
I know it says virtual ports are not supported in the README but I gave LoopMidi a try and it worked initially but now suddenly there appears to be no more MIDI communications. Is this why the README says virtual ports aren't supported on Windows?

I'd like to know if this is worth troubleshooting or if it's already known this won't work reliably.

**Comment by Boddlnagg** [comment]
Virtual ports on Windows require special drivers. loopMIDI is one such special driver. With midir you can only connect to existing ports on Windows, whereas on other OSes you can create virtual ports directly with midir. So if you have issues with loopMIDI, that is completely independent of midir. Once the virtual ports are set up (with loopMIDI or similar software), you should be able to connect to them with midir, because from midir's point of view they are indistinguishable from "real" MIDI devices. If something doesn't work there, maybe try reinstalling loopMIDI. But it doesn't have anything to do with midir.

**Comment by bpmb82** [comment]
Thanks, that's all I needed to know. It turned out to be an issue with the Windows VM I was running, running it on my Windows PC works flawlessly.

Thanks for midir!
