### ISSUE TITLE
Consider using some error management library

### ISSUE THREAD

**Issue by Boddlnagg** [Boddlnagg/midir#17]
See https://github.com/brson/error-chain, or probably https://github.com/withoutboats/failure is better

**Comment by faern** [comment]
`error-chain` is completely dead since long now. And `failure` is not really maintained any longer. The current maintainer even recommend people to switch over to other libraries.

`failure` kind of lost it's charm when the standard library `Error` trait was improved to the degree that it was basically equivalent to `failure::Fail`.

**Comment by Boddlnagg** [comment]
Yes, after reading https://boats.gitlab.io/blog/post/failure-to-fehler/ it looks like it's now best practice to just use the standard `Error` trait.

It shows that midir is already quite an old project and the Rust language has constantly been improving :-)

**Comment by Boscop** [comment]
Another alternative would be [`thiserror`](https://github.com/dtolnay/thiserror). The public API of the lib will just be the std `Error` trait.

> This library provides a convenient derive macro for the standard library's std::error::Error trait. 

> Thiserror deliberately does not appear in your public API. You get the same thing as if you had written an implementation of std::error::Error by hand, and switching from handwritten impls to thiserror or vice versa is not a breaking change.
