### ISSUE TITLE
Can it read and write mid files?

### ISSUE THREAD

**Issue by vi** [Boddlnagg/midir#20]
In either case, it should be in README (if can't then there should be a link to a crate for this using data types from this crate).

**Comment by Boddlnagg** [comment]
No, it cannot (yet). You are right, the sentence "A higher-level API for parsing and assembling MIDI messages might be added in the future." should also mention reading/writing MIDI files.

A quick search on crates.io turned up https://github.com/RustAudio/rimd, which is probably what you are looking for. It does not use data types from this crate, but midir basically does not define any data types since it uses plain byte buffers (`&[u8]`) for messages.
