### ISSUE TITLE
Implement `Send` on everything

### ISSUE THREAD

**Issue by negamartin** [Boddlnagg/midir#36]
Hello.
I've noticed that MidiOutputConnection implements `Send`, and it's quite a useful feature.
However, other structs don't seem to implement it, which surprised me because MidiInputConnection is used only as a token to keep the connection alive.
Is it possible to make input connections, and for that matter the rest of the structs, implement `Send`, or am I missing something important that disallows this?

**Comment by Boddlnagg** [comment]
Actually I had already added a comment that all the structs should implement send:
https://github.com/Boddlnagg/midir/blob/5e90714e5bd5eb9062c19ca1d934dfec767d9711/src/common.rs#L10

I've only done it for `MidiOutputConnection` consistently on all the backends so far, because I needed that for one of the examples. Ideally I would want to be 100% sure that sending midi connections to others threads is actually supported by all the backends, but I don't really know of any reason why it shoudn't.

So I'm definitely going to look into this soon. Thanks for the report!

**Comment by Boddlnagg** [comment]
This has been fixed by #38
