### ISSUE TITLE
Virtual ports support on Windows

### ISSUE THREAD

**Issue by notdanilo** [Boddlnagg/midir#37]
Why virtual ports aren't supported on Windows?

**Comment by Boddlnagg** [comment]
Because Windows just doesn't support them. To get similar functionality on Windows you need to install a custom MIDI driver such as https://www.tobias-erichsen.de/software/virtualmidi.html or http://www.nerds.de/en/loopbe1.html.

Why Windows doesn't have them is a question that you would need to direct at Microsoft.

**Comment by Boscop** [comment]
I'm using loopMidi by Tobias Erichsen, it's free and works without problems. 
I also used his rtpMidi software before, with TouchDAW and to send Midi from my Raspberry Pi to my laptop with this:
https://github.com/ravelox/pimidi/tree/master/raveloxmidi
