### ISSUE TITLE
Report error codes 

### ISSUE THREAD

**Issue by xobs** [Boddlnagg/midir#64]
When connecting, if an error occurs a `ConnectError::Other(s)` is generated:

https://github.com/Boddlnagg/midir/blob/253ae732e94b40f0d4c30be0819f93a5e4107638/src/backend/winmm/mod.rs#L205-L207

This swallows the Windows error code, which could be any of the following:

Value | Description
-- | --
MMSYSERR_ALLOCATED | The specified resource is already allocated.
MMSYSERR_BADDEVICEID | The specified device identifier is out of range.
MMSYSERR_INVALFLAG | The flags specified by dwFlags are invalid.
MMSYSERR_INVALPARAM | The specified pointer or structure is invalid.
MMSYSERR_NOMEM | The system is unable to allocate or lock memory.

It would be nice if the reason for the failure were reported, rather than "could not create Windows MM MIDI input port"

**Comment by Boddlnagg** [comment]
I agree that this can and should be improved. I'm not sure how to best do it, though ... would it help you if the message string would contain the original MM error code? With the current definition of `ConnectErrorKind::Other(&'static str)` I would need to explicitly check for all possible values and translate them into an appropriate message string literal. So I could do something like this:

```rust
 if result == MMSYSERR_ALLOCATED { 
     return Err(ConnectError::other("could not create Windows MM MIDI input port (MMSYSERR_ALLOCATED)", self)); 
 } else if ...
```

Would that be sufficient? The documentation at https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/nf-mmeapi-midiinopen#return-value does leave it open that there might be more error codes, but I don't know how that should be handled ...

Also, I'm pretty sure that not all of the five error codes that are listed can actually occur, because at least `MMSYSERR_INVALPARAM` should never happen.

`MMSYSERR_BADDEVICEID` should not happen either, but theoretically can occur in the very rare case that a port disappears (e.g.  device is unplugged) between resolving the port number and the call to `midiInOpen` ... but in that case it could also happen that the device numbering changes and you end up connected to a *different* device than the one you requested 😕

Do you think that the problem in your original issue  was `MMSYSERR_ALLOCATED` (i.e., is that the code that you get when the device is already open in another program)?

**Comment by xobs** [comment]
The user who reported https://github.com/xobs/midi-to-keypress/issues/4 did have the device open in another program, so I suspect that `MMSYSERR_ALLOCATED` is the most common error we will receive, and should probably get special treatment. The others are less likely to happen, and maybe it's enough to simply treat `MMSYSERR_ALLOCATED` as a special case.

I'd argue that `MMSYSERR_ALLOCATED` should return a more friendly string along the lines of "could not create Windows MM MIDI input port -- device is already being used".

You could do something like:

```rust
if result == MMSYSERR_ALLOCATED { 
     return Err(ConnectError::other("could not create Windows MM MIDI input port (MMSYSERR_ALLOCATED)", self)); 
} else if result != MMSYSERR_NOERROR {
     return Err(ConnectError::other(format!("could not create Windows MM MIDI input port (result: 0x{:x)", result), self)); 
}
```

And that would let us read through the tea leaves rather than shipping a special build. If other errors come up more often, then they can also be special-cased.

Note that this will also need to be replicated for the output port error, which has a similar path.

**Comment by Boddlnagg** [comment]
> You could do something like:

```rust
if result == MMSYSERR_ALLOCATED { 
     return Err(ConnectError::other("could not create Windows MM MIDI input port (MMSYSERR_ALLOCATED)", self)); 
} else if result != MMSYSERR_NOERROR {
     return Err(ConnectError::other(format!("could not create Windows MM MIDI input port (result: 0x{:x)", result), self)); 
}
```

No, I can't use `format!(...)`, because that returns a `String` and I can only use static string constants with how `ConnectError::Other` is currently designed. I could change this to allocate a `String`, but there was no need so far ...

**Comment by xobs** [comment]
Ah, then yes, your approach is fine. No point in bikeshedding here -- the most common error is almost certainly `MMSYSERR_ALLOCATED`.

**Comment by Boddlnagg** [comment]
Should be fixed in `master` now. I'm going to release 0.7.0 soon(ish) (#68)
