### ISSUE TITLE
How to connect to *all* ports?

### ISSUE THREAD

**Issue by piegamesde** [Boddlnagg/midir#67]
I know there is an issue asking for multi-port support which won't be implement, so I'll need to create a new `MidiInput` client for each port. But on the other hand, I already need a `MidiInput` client to be able to enumerate all available ports. So, what's the ~~least ugly~~ best way to listen to all ports at once?

**Comment by Boddlnagg** [comment]
Sorry, what do you mean by "all ports"? Really all the input ports that are available in the system? I see that this is a bit tricky currently, because connecting to a port consumes the `MidiInput` structure, and you have to get a new one to connect to further ports.

The problem with supporting a feature such as "connecting to multiple/all ports" is that it has to be implemented for all the backends. So I really have to check if all the backends would support this is some way.

Could you explain your use case a little bit more in detail? That might make it easier for me to explore this.

**Comment by piegamesde** [comment]
> Really all the input ports that are available in the system?

Yes.

> I see that this is a bit tricky currently

That's why I was asking.

--------

My use case is that I need to listen to some incoming events, but it should be plug and play and I don't want to bother the user with some port selection etc. As I didn't find any possibility to distinguish between physical MIDI ports and some irrelevant loopbacks and what not, I thought simply listening to *all* MIDI ports should solve that problem. Those loopback/dummy ports usually don't generate any events, and having multiple physical devices connected should not harm my use case.

**Comment by Boddlnagg** [comment]
> My use case is that I need to listen to some incoming events, but it should be plug and play and I don't want to bother the user with some port selection etc.

Are you sure that the user is not using any other MIDI software at the same time? Because (at least on Windows, don't know about the other backends) you can only establish one connection to each device at the same time. So if a device is already "in use", it won't work.

I'm afraid, I probably won't be able to offer a quick solution anytime soon.

**Comment by piegamesde** [comment]
> you can only establish one connection to each device at the same time

As I only really know JACK, I never thought of this. Indeed, this would be a problem (though blocking a port by listening to it is a problem in general, though blocking *all* won't make it better).

Maybe may best option is to switch to a Unix-only library that does not have to deal with this weird limitations.

**Comment by Boddlnagg** [comment]
> Maybe may best option is to switch to a Unix-only library that does not have to deal with this weird limitations.

Yeah, sorry. I guess this library is just not the right abstraction for all possible use cases. It needs to find the least common denominator across all the platforms 😕
