### ISSUE TITLE
Virtual ports on Raspberry Pi

### ISSUE THREAD

**Issue by nordseele** [Boddlnagg/midir#73]
Hi,
I'm having difficulties creating a virtual Input and a virtual output with the following code. I'm on the latest Rasbian OS on Raspberry PI.

It doesn't return any error however the two ports are not listed in `aconnect -l` 

I'm creating two new midi objects and then calling create_virtual on each of them. 
Am I missing anything here ? Does it need something else ? 

Thanks.

_main.rs_

```
use crate::midi::*;
mod midi;

   match run_midi() {
        Ok(_) => {(); println!("Creating virtual input port ...");},
        Err(err) => println!("Error: {}", err)
    }
```

_midi.rs (module)_ 

```
use std::error::Error;
use midir::{MidiInput, MidiOutput, Ignore};
use midir::os::unix::{VirtualInput, VirtualOutput};

pub fn run_midi() -> Result<(), Box<dyn Error>> {
    let midi_in = MidiInput::new("My Test Input")?;
    let midi_out = MidiOutput::new("My Test Output")?;
    
    midi_in.create_virtual("midir-test", |stamp, message, _| {
        println!("{}: {:?} (len = {})", stamp, message, message.len());
    }, ())?;
    
    midi_out.create_virtual("midir-test")?;
    
    Ok(())
}
```

**Comment by Boddlnagg** [comment]
I think the problem is this: By ignoring the result of the `create_virtual` calls, the virtual ports get closed immediately (you handle the error via `?`, but then you throw away the actual `MidiOutputConnection` / `MidiInputConnection`).
You need to assign them to some variable and then keep them alive.

See https://github.com/Boddlnagg/midir/blob/master/tests/virtual.rs for an example of how to use virtual ports.

**Comment by nordseele** [comment]
Oh that's right, my mistake... Now it's working.
Thanks a lot for your reply and for providing the virtual.rs example.
