### ISSUE TITLE
winrt feature only shows Windows WaveTable Synth

### ISSUE THREAD

**Issue by insomnimus** [Boddlnagg/midir#85]
i have two midi devices installed on my win 10 pc
-  Coolsoft Virtual Midi Synth
-  Microsoft WaveTable Synth (the default one)

i can play with the virtual midi synth if i don't enable the winrt feature but with it enabled it's no longer listed

is this winrt related or is this a bug? s there a way i can use virtual midi synth with winrt enabled?
i want to use winrt because it's more responsive, noticably less delay on input

**Comment by Boddlnagg** [comment]
This is weird, because the WinRT backend doesn't do anything special here. It simply calls
[DeviceInformation::FindAllAsync](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.findallasync?view=winrt-19041#Windows_Devices_Enumeration_DeviceInformation_FindAllAsync_System_String_) with the result of [MidiOutPort::GetDeviceSelector](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi.midioutport.getdeviceselector?view=winrt-19041) ... I have no idea what could go wrong there, except for a bug in the WinRT implementation itself.

You could try to build a minimal reproduction with the current version of [windows-rs](https://github.com/microsoft/windows-rs) and then open a GitHub issue there, with the hope that it gets forwarded to the team at Microsoft that is responsible for the MIDI implementation.

**Comment by insomnimus** [comment]
Yup, i tested it with the windows crate itself and it's only listing the default midi device, closing the issue.
