### ISSUE TITLE
all messages appears to be 'other'

### ISSUE THREAD

**Issue by adsick** [Boddlnagg/midir#89]
Hi, I'm not sure who to blame, but all the messages are 'other'

I'm using Arturia microlab midi keyboard in Linux (Pop!_OS 21.04)
![image](https://user-images.githubusercontent.com/24528839/125174321-452c2b80-e1cd-11eb-9fad-ecc01a89df82.png)
Also tried to play it in SunVox, also see that there is some input, but it does not play the keys

**Comment by Boddlnagg** [comment]
I'm a bit confused, what code are you using to print these messages? In the original `test_read_input` example that is part of the repository, the printing is done here:

https://github.com/Boddlnagg/midir/blob/e1064da9b57b480a6ad49fb0c27becb0540cb2d7/examples/test_read_input.rs#L48

So the first parameter should be the timestamp. But `Other:G4 - Raw` doesn't look like a timestamp at all ...
Did you change the code? Are you using the ALSA backend (probably because it's the default on Linux)?

**Comment by adsick** [comment]
> I'm a bit confused, what code are you using to print these messages? In the original `test_read_input` example that is part of the repository, the printing is done here:

I am in fact using [bevy_midi](https://github.com/BlackPhlox/bevy_midi)
(piano example)

**Comment by Boddlnagg** [comment]
In that case you probably want to open an issue in that repository? Because I'm not sure how I can help.
If it turns out to actually be a specific issue with `midir` itself, feel free to reopen.
